import os


AWS_KEY = "ACCESS_KEY_ID"
AWS_SECRET = "SECRET_ACCESS_KEY"
AWS_SESSION = "SESSION_TOKEN"
S3_BUCKET = "S3_BUCKET"
DYNAMODB_TABLE = "DYNAMODB_TABLE"
SECRET_KEY = os.urandom(32)
DEBUG = False
PORT = 5000
